### ISSUE TITLE
padding error

### ISSUE THREAD

**Issue by skeletondyh** [cezannec/CNN_Text_Classification#2]
Hi! 
I suppose the padding in ConvNet should be 0 along the width

padding = (k - 2, 0) instead of padding = k - 2

Otherwise the following squeeze op would fail

**Comment by skeletondyh** [comment]
Since squeeze would only remove dimension of size 1

**Comment by youben11** [comment]
+1 on this @cezannec. We have to make the padding along the width 0 so we don't make multiple convolutions along the width dimension. So in the `In [23]:` padding should be (k - 2, 0)

**Comment by cezannec** [comment]
Ah, thank you for bringing this to my attention (again!) you are absolutely right. I'll run this updated code and I bet the results will be even more accurate!
